# Generated by Django 6.0.5 on 2026-06-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('heure', models.FloatField()),
                ('nb_transactions_24h', models.FloatField()),
                ('distance_domicile', models.FloatField()),
                ('pays_etranger', models.BooleanField(default=False)),
                ('nouvelle_carte', models.BooleanField(default=False)),
                ('est_fraud', models.BooleanField(default=False)),
                ('probabilite_fraude', models.FloatField(default=0.0)),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-date_analyse'],
            },
        ),
    ]
